"""init

Revision ID: 44ffa7b8bf87
Revises: 
Create Date: 2026-05-03 03:49:44.866425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ffa7b8bf87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('virtual_iban', sa.String(length=34), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('wallet_id'),
    sa.UniqueConstraint('virtual_iban')
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.create_table('fund_requests',
    sa.Column('fund_request_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'paid', 'failed', name='fundrequeststatus', native_enum=False), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('top_up', 'fund_transfer', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.wallet_id'], ),
    sa.PrimaryKeyConstraint('fund_request_id')
    )
    op.create_index(op.f('ix_fund_requests_idempotency_key'), 'fund_requests', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_fund_requests_wallet_id'), 'fund_requests', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_requests_wallet_id'), table_name='fund_requests')
    op.drop_index(op.f('ix_fund_requests_idempotency_key'), table_name='fund_requests')
    op.drop_table('fund_requests')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
