"""init

Revision ID: d9b668b22b69
Revises: 
Create Date: 2026-05-03 03:50:30.412409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b668b22b69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statements',
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.String(length=255), nullable=False),
    sa.Column('virtual_iban', sa.String(length=34), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.Enum('top_up', 'fund_transfer', name='transactiontype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'reconciled', name='statementstatus', native_enum=False), nullable=False),
    sa.Column('fund_request_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('statement_id')
    )
    op.create_index(op.f('ix_statements_reference'), 'statements', ['reference'], unique=True)
    op.create_index(op.f('ix_statements_virtual_iban'), 'statements', ['virtual_iban'], unique=False)
    op.create_index(op.f('ix_statements_wallet_id'), 'statements', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statements_wallet_id'), table_name='statements')
    op.drop_index(op.f('ix_statements_virtual_iban'), table_name='statements')
    op.drop_index(op.f('ix_statements_reference'), table_name='statements')
    op.drop_table('statements')
    # ### end Alembic commands ###
